/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { createFileRoute } from '@tanstack/react-router';
import type { createStart } from '@tanstack/react-start';

import type { getRouter } from './router.tsx';
import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';

const PaymentMethodsLazyRouteImport = createFileRoute('/payment-methods')();
const InternalTriageFormLazyRouteImport = createFileRoute(
  '/internal-triage-form'
)();

const PaymentMethodsLazyRoute = PaymentMethodsLazyRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/payment-methods.lazy').then((d) => d.Route)
);
const InternalTriageFormLazyRoute = InternalTriageFormLazyRouteImport.update({
  id: '/internal-triage-form',
  path: '/internal-triage-form',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/internal-triage-form.lazy').then((d) => d.Route)
);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/internal-triage-form': typeof InternalTriageFormLazyRoute;
  '/payment-methods': typeof PaymentMethodsLazyRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/internal-triage-form': typeof InternalTriageFormLazyRoute;
  '/payment-methods': typeof PaymentMethodsLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/internal-triage-form': typeof InternalTriageFormLazyRoute;
  '/payment-methods': typeof PaymentMethodsLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/internal-triage-form' | '/payment-methods';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/internal-triage-form' | '/payment-methods';
  id: '__root__' | '/' | '/internal-triage-form' | '/payment-methods';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  InternalTriageFormLazyRoute: typeof InternalTriageFormLazyRoute;
  PaymentMethodsLazyRoute: typeof PaymentMethodsLazyRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-methods': {
      id: '/payment-methods';
      path: '/payment-methods';
      fullPath: '/payment-methods';
      preLoaderRoute: typeof PaymentMethodsLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/internal-triage-form': {
      id: '/internal-triage-form';
      path: '/internal-triage-form';
      fullPath: '/internal-triage-form';
      preLoaderRoute: typeof InternalTriageFormLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalTriageFormLazyRoute: InternalTriageFormLazyRoute,
  PaymentMethodsLazyRoute: PaymentMethodsLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
