/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternalTriageFormRouteImport } from './routes/internal-triage-form'
import { Route as IndexRouteImport } from './routes/index'

const InternalTriageFormRoute = InternalTriageFormRouteImport.update({
  id: '/internal-triage-form',
  path: '/internal-triage-form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/internal-triage-form': typeof InternalTriageFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/internal-triage-form': typeof InternalTriageFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/internal-triage-form': typeof InternalTriageFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/internal-triage-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/internal-triage-form'
  id: '__root__' | '/' | '/internal-triage-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternalTriageFormRoute: typeof InternalTriageFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/internal-triage-form': {
      id: '/internal-triage-form'
      path: '/internal-triage-form'
      fullPath: '/internal-triage-form'
      preLoaderRoute: typeof InternalTriageFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalTriageFormRoute: InternalTriageFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
